
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class giaodien extends javax.swing.JFrame {

    /**
     * Creates new form giaodien
     */
    public giaodien() {
        initComponents();
        lberror.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ceasar_banro = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ceasar_banma = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        ceasar_key = new javax.swing.JTextField();
        ceasar_mahoa = new javax.swing.JButton();
        ceasar_giaima = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        subti_key = new javax.swing.JTextField();
        subti_mahoa = new javax.swing.JButton();
        subti_giaima = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        subti_banro = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        subti_banma = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        apphine_a = new javax.swing.JTextField();
        apphine_mahoa = new javax.swing.JButton();
        apphine_giaima = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        apphine_banro = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        apphine_banma = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        apphine_b = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        vigene_banma = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vigene_m = new javax.swing.JTextField();
        vigene_keyword = new javax.swing.JTextField();
        vigene_mahoa = new javax.swing.JButton();
        vigene_giaima = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        vigene_banro = new javax.swing.JTextArea();
        lberror = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hill_b = new javax.swing.JTextField();
        hill_a = new javax.swing.JTextField();
        hill_d = new javax.swing.JTextField();
        hill_c = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        hill_banma = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        hill_banro = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        hill_mahoa = new javax.swing.JButton();
        hill_giaima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Bản rõ:");

        ceasar_banro.setColumns(20);
        ceasar_banro.setRows(5);
        jScrollPane1.setViewportView(ceasar_banro);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Bản mã:");

        ceasar_banma.setColumns(20);
        ceasar_banma.setRows(5);
        jScrollPane2.setViewportView(ceasar_banma);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nhập khoá k:");

        ceasar_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceasar_keyActionPerformed(evt);
            }
        });

        ceasar_mahoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ceasar_mahoa.setText("Mã hoá");

        ceasar_giaima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ceasar_giaima.setText("Giải mã");
        ceasar_giaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceasar_giaimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(ceasar_key, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(ceasar_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ceasar_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ceasar_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceasar_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceasar_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ceasar", jPanel1);

        subti_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subti_keyActionPerformed(evt);
            }
        });

        subti_mahoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subti_mahoa.setText("Mã hoá");

        subti_giaima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subti_giaima.setText("Giải mã");
        subti_giaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subti_giaimaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bản rõ:");

        subti_banro.setColumns(20);
        subti_banro.setRows(5);
        jScrollPane3.setViewportView(subti_banro);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Bản mã:");

        subti_banma.setColumns(20);
        subti_banma.setRows(5);
        jScrollPane4.setViewportView(subti_banma);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nhập khoá (một hoán vị bất kì của bảng chữ cái alphabet):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(subti_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subti_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(subti_key, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subti_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subti_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subti_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mã hoán vị", jPanel2);

        apphine_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apphine_aActionPerformed(evt);
            }
        });

        apphine_mahoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apphine_mahoa.setText("Mã hoá");
        apphine_mahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apphine_mahoaActionPerformed(evt);
            }
        });

        apphine_giaima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apphine_giaima.setText("Giải mã");
        apphine_giaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apphine_giaimaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Bản rõ:");

        apphine_banro.setColumns(20);
        apphine_banro.setRows(5);
        jScrollPane5.setViewportView(apphine_banro);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bản mã:");

        apphine_banma.setColumns(20);
        apphine_banma.setRows(5);
        jScrollPane6.setViewportView(apphine_banma);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nhập số a:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nhập số b:");

        apphine_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apphine_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(apphine_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apphine_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(apphine_a, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(apphine_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(apphine_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(apphine_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apphine_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apphine_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Affine", jPanel3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Bản mã:");

        vigene_banma.setColumns(20);
        vigene_banma.setRows(5);
        jScrollPane7.setViewportView(vigene_banma);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nhập khoá m:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nhập keyword:");

        vigene_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigene_mActionPerformed(evt);
            }
        });
        vigene_m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vigene_mKeyPressed(evt);
            }
        });

        vigene_keyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigene_keywordActionPerformed(evt);
            }
        });

        vigene_mahoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vigene_mahoa.setText("Mã hoá");
        vigene_mahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigene_mahoaActionPerformed(evt);
            }
        });

        vigene_giaima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vigene_giaima.setText("Giải mã");
        vigene_giaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigene_giaimaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Bản rõ:");

        vigene_banro.setColumns(20);
        vigene_banro.setRows(5);
        jScrollPane8.setViewportView(vigene_banro);

        lberror.setText("jLabel22");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(vigene_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vigene_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vigene_keyword, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vigene_m, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lberror, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(vigene_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lberror))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(vigene_keyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vigene_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vigene_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vigenere", jPanel4);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nhập ma trận khoá K:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("a:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("c:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("b:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("d:");

        hill_banma.setColumns(20);
        hill_banma.setRows(5);
        jScrollPane9.setViewportView(hill_banma);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Bản rõ:");

        hill_banro.setColumns(20);
        hill_banro.setRows(5);
        jScrollPane10.setViewportView(hill_banro);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Bản mã:");

        hill_mahoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hill_mahoa.setText("Mã hoá");

        hill_giaima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hill_giaima.setText("Giải mã");
        hill_giaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hill_giaimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(jLabel16)))
                            .addComponent(hill_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hill_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hill_c, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hill_b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hill_d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hill_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(hill_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hill_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(hill_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hill_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hill_mahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hill_giaima, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Hill", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void ceasar_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceasar_keyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ceasar_keyActionPerformed

    private void ceasar_giaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceasar_giaimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceasar_giaimaActionPerformed

    private void subti_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subti_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subti_keyActionPerformed

    private void subti_giaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subti_giaimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subti_giaimaActionPerformed

    private void apphine_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apphine_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apphine_aActionPerformed

    private void apphine_giaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apphine_giaimaActionPerformed
        // TODO add your handling code here:
         if (apphine_banma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "không được bỏ trống ban ma");
        }   
              else  if (apphine_a.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "không được bỏ trống a ");
        } 
                else    if (apphine_b.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "không được bỏ trống b");
        } 
            char[] ban_ro=new char[100];
            char[] ban_ma=new char[100];
             int nghich_dao=0;
             
            String banma=apphine_banma.getText();
             int a= Integer.parseInt(apphine_a.getText()); 
             int b= Integer.parseInt(apphine_b.getText());
             for (int i = 0; i < banma.length(); i++) {
                  ban_ma[i]=banma.charAt(i);
                  }
           
            for (int i=1; i < 26; i++) {
              if (( a * i) % 26 == 1) {
                nghich_dao=i;
               break;
              }
            }
  
              for (int i = 0; i < banma.length(); i++)
          {
        char c = ban_ma[i];
       if (c >= 'A' && c <= 'Z'){
           if((c - 'A' - b)<0)
            ban_ro[i] = (char) (nghich_dao * (c - 'A' - b + 26) % 26 + 'A');
           else
               ban_ro[i] = (char) (nghich_dao*(c - 'A' - b) % 26 + 'A');
       }
        else if (c >= 'a' && c <= 'z'){
             if ((c - 'a' - b) < 0)
            ban_ro[i] = (char) (nghich_dao * (c - 'a' - b +26)  %26 + 'a');   
             else
                   ban_ro[i] = (char) (nghich_dao*(c - 'a' - b) % 26 + 'a');   
           }
          }
   
              
              String giai_ma=String.copyValueOf(ban_ro); 
               apphine_banro.setText(giai_ma);
    }//GEN-LAST:event_apphine_giaimaActionPerformed

    private void apphine_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apphine_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apphine_bActionPerformed

    private void vigene_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigene_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vigene_mActionPerformed

    private void vigene_keywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigene_keywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vigene_keywordActionPerformed

    private void vigene_giaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigene_giaimaActionPerformed
        // TODO add your handling code here:

        int mflag = 0, keyflag = 0;
        String errortext="";
        if(mflag == 1){
            errortext += "Khoá m ";
        }
        if(keyflag == 1){
            if(!errortext.isEmpty()) errortext += ",keyword ";
            errortext += "Keyword ";
        }
        if(!errortext.isEmpty()){
            JOptionPane.showMessageDialog(null,errortext + " bị trống, hãy nhập đủ thông tin cần thiết để giải mã!");
            
        }
        if(vigene_banma.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Hiện không có bản mã, không thể giải mã!");
        }
        else{
            String banma = vigene_banma.getText().trim();
            String key = vigene_keyword.getText().trim();
            int m = Integer.parseInt(vigene_m.getText());
            String alphabet = "abcdefghijklmnopqrstuvwxyz";
            int a = 1;
            int dem = 0;
            String plaintext = "";
            for(int i=0; i< banma.length();i++){
                    if(dem == m){
                            dem = 0;
                    }
                    if(dem<m){
                            if(Character.isUpperCase(banma.charAt(i))){
                                    int machar = banma.charAt(i) - 65;
                                    int keychar = key.charAt(dem) - 65;
                                    int c = (machar - keychar) + 26;
                                    int last = c % 26;
                                    plaintext += alphabet.charAt(last);
                            }else{
                                    int machar = banma.charAt(i) - 97;
                                    int keychar = key.charAt(dem) - 97;
                                    int c = (machar - keychar) + 26;
                                    int last = c % 26;
                                    plaintext += alphabet.charAt(last);
                                    //plaintext+= machar + " "+ keychar + " " + c + " " + last + " " + "\n";
                            }
                            dem++;
                    }

            }
            if(!plaintext.isEmpty()){
                JOptionPane.showMessageDialog(null,"Giải mã thành công!");
                vigene_banro.setText(plaintext);
            }
        }
      
    }//GEN-LAST:event_vigene_giaimaActionPerformed

    private void hill_giaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hill_giaimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hill_giaimaActionPerformed

    private void vigene_mahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigene_mahoaActionPerformed
        // TODO add your handling code here:
        String errortext="";
        int banroflag = 0, mflag = 0, keyflag = 0;
        if(vigene_banro.getText().equals("")){
            banroflag = 1;
        }
        if(vigene_m.getText().equals("")){
            mflag = 1;
        }
        if(vigene_keyword.getText().equals("")){
            keyflag = 1;
        }
        if(banroflag == 1){
            errortext += "Bản rõ ";
        }
        if(mflag == 1){
            if(!errortext.isEmpty()) errortext += ",khoá m ";
            errortext += "Khoá m ";
        }
        if(keyflag == 1){
            if(!errortext.isEmpty()) errortext += ",keyword ";
            errortext += "Keyword ";
        }
        if(!errortext.isEmpty()){
            JOptionPane.showMessageDialog(null,errortext + " bị trống, hãy nhập đầy đủ thông tin!");
            
        }
        else{
            String banro = vigene_banro.getText().trim();
            String key = vigene_keyword.getText().trim();
            int m = Integer.parseInt(vigene_m.getText());
            String alphabet = "abcdefghijklmnopqrstuvwxyz";
            String alphabet2 = "";
            int dem = 0;
            String mahoatext = "";
            for(int i=0; i< banro.length();i++){
                    if(dem == m){
                            dem = 0;
                    }
                    if(dem<m){
                            if(Character.isUpperCase(banro.charAt(i))){
                                    int temp = banro.charAt(i)-65 + key.charAt(dem)-65;
                                    int c = temp % 26;
                                    mahoatext+= alphabet.charAt(c);
                            }else{
                                    int temp = banro.charAt(i)-97 + key.charAt(dem)-97;
                                    int c = temp % 26;
                                    mahoatext+= alphabet.charAt(c);
                            }
                            dem++;
                    }


            }
            if(!mahoatext.isEmpty()){
                JOptionPane.showMessageDialog(null,"Mã hoá thành công!");
                vigene_banma.setText(mahoatext);
            }
        }
    }//GEN-LAST:event_vigene_mahoaActionPerformed

    private void vigene_mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vigene_mKeyPressed
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if(Character.isLetter(c)){
            vigene_m.setEditable(false);
            lberror.setVisible(true);
            lberror.setText("Chỉ nhập số cho khoá m");
            lberror.setForeground(Color.red);
        }
        else{
            vigene_m.setEditable(true);
            lberror.setVisible(false);
        }
    }//GEN-LAST:event_vigene_mKeyPressed

    private void apphine_mahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apphine_mahoaActionPerformed
        // TODO add your handling code here:
        if (apphine_banro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "không được bỏ trống ban ro");
        }   
              else  if (apphine_a.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "không được bỏ trống a ");
        } 
                else    if (apphine_b.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "không được bỏ trống b");
        } 
            char[] ban_ro=new char[100];
            char[] ban_ma=new char[100];
             String ma_hoa;
             
            String banro=apphine_banro.getText();
             int a= Integer.parseInt(apphine_a.getText()); 
             int b= Integer.parseInt(apphine_b.getText());
             for (int i = 0; i < banro.length(); i++) {
                  ban_ro[i]=banro.charAt(i);
                  }
             
              for (int i = 0; i < banro.length(); i++)
          {
        char c = ban_ro[i];
       if (c >= 'A' && c <= 'Z')
            ban_ma[i] = (char) ((a*(c - 'A')+b) % 26 + 'A');
        else if (c >= 'a' && c <= 'z')
            ban_ma[i] = (char) ((a*(c - 'a') + b) % 26 + 'a');   
           }
              
               ma_hoa=String.copyValueOf(ban_ma); 
               apphine_banma.setText(ma_hoa);
    }//GEN-LAST:event_apphine_mahoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giaodien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apphine_a;
    private javax.swing.JTextField apphine_b;
    private javax.swing.JTextArea apphine_banma;
    private javax.swing.JTextArea apphine_banro;
    private javax.swing.JButton apphine_giaima;
    private javax.swing.JButton apphine_mahoa;
    private javax.swing.JTextArea ceasar_banma;
    private javax.swing.JTextArea ceasar_banro;
    private javax.swing.JButton ceasar_giaima;
    private javax.swing.JTextField ceasar_key;
    private javax.swing.JButton ceasar_mahoa;
    private javax.swing.JTextField hill_a;
    private javax.swing.JTextField hill_b;
    private javax.swing.JTextArea hill_banma;
    private javax.swing.JTextArea hill_banro;
    private javax.swing.JTextField hill_c;
    private javax.swing.JTextField hill_d;
    private javax.swing.JButton hill_giaima;
    private javax.swing.JButton hill_mahoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lberror;
    private javax.swing.JTextArea subti_banma;
    private javax.swing.JTextArea subti_banro;
    private javax.swing.JButton subti_giaima;
    private javax.swing.JTextField subti_key;
    private javax.swing.JButton subti_mahoa;
    private javax.swing.JTextArea vigene_banma;
    private javax.swing.JTextArea vigene_banro;
    private javax.swing.JButton vigene_giaima;
    private javax.swing.JTextField vigene_keyword;
    private javax.swing.JTextField vigene_m;
    private javax.swing.JButton vigene_mahoa;
    // End of variables declaration//GEN-END:variables
}
